# Generated by Django 6.0.7 on 2026-08-02 21:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('registration', models.CharField(help_text='Format: UICT/2026/0001', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must look like UICT/2026/0001', regex='^UICT/\\d{4}/\\d{4}$')])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('course', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
