# Generated by Django 6.0.7 on 2026-08-02 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Stable dedupe key, e.g. 'borrow_BK001' or 'due_BK001_2026-08-10'.", max_length=100)),
                ('type', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('overdue', 'Overdue'), ('info', 'Info')], default='info', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'key')},
            },
        ),
    ]
